# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
        with:
          elixir-version: '1.17.3' # [Required] Define the Elixir version
          otp-version: '27.0'      # [Required] Define the Erlang/OTP version
      - name: Run formatter
        run: mix format --check-formatted
  escript:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build and install escript
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: prod
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.17.3' # [Required] Define the Elixir version
        otp-version: '27.0'      # [Required] Define the Erlang/OTP version
    - name: Build escript
      run: mix escript.build
    - name: Check binary
      run: ./fr --help
  escript_macos:
    name: Build and install escript (macos)
    runs-on: macos-latest
    env:
      MIX_ENV: prod
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      run: brew install elixir
    - name: Set up hex
      run: mix local.hex --force
    - name: Build escript
      run: mix escript.build
    - name: Check binary
      run: ./fr --help
  testsuite:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.17.3' # [Required] Define the Elixir version
        otp-version: '27.0'      # [Required] Define the Erlang/OTP version
    - name: Run tests
      run: mix test
  testsuite_macos:
    name: Run unit tests (macos)
    runs-on: macos-latest
    env:
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      run: brew install elixir
    - name: Set up hex
      run: mix local.hex --force
    - name: Run tests
      run: mix test
